release:
  prerelease: false

builds:
  - binary: kafka-stress
    env:
      - TOP=0
    goos:
      - windows
      - darwin
      - linux
      - freebsd
    goarch:
      - amd64
      - arm64

# brews:
#   - github:
#       owner: msfidelis
#       name: homebrew-kafka-stress
#     homepage: "https://github.com/msfidelis/kafka-stress/"
#     description: "Kafka Producer / Consumer Stress Test Tool"

archives:
  - format: binary
    format_overrides:
      - goos: windows
        format: zip